### ISSUE TITLE
Error onPostBuild lifecycle - not found: yarn

### ISSUE THREAD

**Issue by kramerkm** [percy/gatsby-plugin-percy#10]
Running into an issue on the post build piece with yarn not being found.

```
not found: yarn

   7 |   let { program: { useYarn, directory } } = store.getState()
   8 | 
>  9 |   let manager = which.sync(useYarn ? 'yarn' : 'npx')
     |                       ^
  10 |   let cmd = [manager, 'percy', 'snapshot', path.resolve(directory, 'public')]
  11 | 
  12 |   if (files) {

File: node_modules/gatsby-plugin-percy/gatsby-node.js:9:23
```

Running version 2.20.9 of Gatsby with version 0.1.4 of gatsby-plugin-percy.

**Comment by wwilsman** [comment]
Hey @kramerkm! I believe `useYarn` is derived from Gatsby by checking if the project contains a `yarn.lock` file. So if you're getting an error about yarn not being found, that means it isn't available where ever your project is being built, but Gatsby assumes it is available since it finds the lockfile.
